platform :ios, '11.0'
use_frameworks!

target 'CurrencyQuiz' do
  pod 'Alamofire', '~> 5.6'
  pod 'ObjectMapper', '~> 4.2'
  pod 'ObjectMapper+Realm'
  pod 'RealmSwift', '~> 10.36'
  pod 'PopupDialog', '~> 1.1'

end
