//
//  MainPresenter.swift
//  CurrencyQuiz
//
//  Created by GA007295 on 26/2/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentCurrentPrice(response: Main.CurrentPrice.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentCurrentPrice(response: Main.CurrentPrice.Response)
    {
        let viewModel = Main.CurrentPrice.ViewModel(currencyPrice: response.currencyPrice)
        viewController?.displayCurrentPrice(viewModel: viewModel)
    }
}
